/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Res {

  static const String home = "assets/images/home.png";
  static const String wallet = "assets/images/wallet.png";
  static const String account = "assets/images/user.png";
  static const String credit = "assets/images/credit.png";
  static const String walletb = "assets/images/walletb.png";
  static const String walletcircle = "assets/images/walletcircle.png";
}
